/* English dictionary — loaded when lang=en (or fallback).
 *
 * Conventions:
 *   - flat keys with dotted namespaces (settings.background, common.yes)
 *   - plural forms use dotted suffixes: key.one / key.few / key.many / key.other
 *   - placeholder syntax: {name} in the value, passed as t('key', {name: 'X'})
 *   - missing key → runtime returns the key string (easy to spot in UI)
 */
window.I18N = {
    /* ── common ───────────────────────────────────────────── */
    "common.yes":                 "Yes",
    "common.no":                  "No",
    "common.cancel":              "Cancel",
    "common.save":                "Save",
    "common.confirm":             "Confirm",
    "common.error":               "Error",
    "common.warning":             "WARNING",
    "common.remove":              "Remove",
    "common.loading":             "loading",
    "common.not_set":             "Not set",
    "common.last_change":         "Last change {date}",
    "common.code":                "Code",
    "common.lang_en":             "English",
    "common.lang_ru":             "Russian",
    "common.lang_uk":             "Ukrainian",

    /* ── plurals: {n} ─────────────────────────────────────── */
    "common.victims.one":         "{n} victim",
    "common.victims.other":       "{n} victims",

    /* ── settings page (tab + table labels) ──────────────── */
    "settings.tab_main":          "main",
    "settings.background":        "Background",
    "settings.color":             "Color",
    "settings.sound":             "Sound",
    "settings.default_ws_server": "Default WS server",
    "settings.language":          "Language",
    "settings.login":             "Login:",
    "settings.registration_date": "Registration date:",
    "settings.your_mail":         "Your mail:",
    "settings.password":          "Password:",
    "settings.two_factor":        "Two-factor authentication:",
    "settings.two_factor.enabled":  "Enabled",
    "settings.two_factor.disabled": "Disabled",
    "settings.log_out":           "Log out",
    "settings.delete_acc":        "Delete acc",
    "settings.enabled":           "Enabled",
    "settings.disabled":          "Disabled",

    /* ── popups in settings (titles + body) ───────────────── */
    "settings.remove_email":      "Remove email",
    "settings.set_email":         "Set email",
    "settings.change_password":   "Change password",
    "settings.activate_2fa":      "Activate 2fa",
    "settings.delete_2fa":        "Delete 2fa",
    "settings.delete_account":    "Delete account",
    "settings.logout_q":          "Logout?",
    "settings.end_all_sessions":  "End all sessions",

    "settings.code_sent":         "code sent to mail, check spam",
    "settings.placeholder_code_from_mail": "Code from mail",
    "settings.placeholder_new_mail":        "New mail",
    "settings.placeholder_old_password":    "Old password",
    "settings.placeholder_new_password":    "New password",
    "settings.placeholder_new_password_2":  "New password again",
    "settings.placeholder_password":        "Password",
    "settings.placeholder_code":            "code",
    "settings.placeholder_your_password":   "your password",
    "settings.scan_qr_hint":     "Scan QR code via authenticator or import secret code",
    "settings.secret_code":       "Secret code",
    "settings.save_recovery":     "PLZ SAVE THIS CODE",
    "settings.save_recovery_sub": "WRITE IT ON PAPER AND PUT IN THE SAFE BOX",
    "settings.i_saved_it":        "I saved this code",

    /* ── delete account warnings ─────────────────────────── */
    "settings.warn_title":        "☠ Warning ☠",
    "settings.warn_forever":      "Access will be lost <b>forever</b>.",
    "settings.warn_username":     "Username will remain unavailable for registration.",
    "settings.warn_mail_2fa":     "Mail and 2fa unlinking is required.",
    "settings.warn_delete_forever": "Delete forever",

    /* ── misc UI strings the engine renders from JS ──────── */
    "settings.err_pass_too_short":   "Password: 5 chars min.",
    "settings.err_passwords_mismatch": "Passwords do not match",
    "settings.err_invalid_email":    "Enter a valid email!",
    "settings.msg_relogin":          "plz relogin",
    "settings.captcha_slide":        "Slide to Verify →",
    "settings.captcha_verified":     "VERIFIED",
    "settings.captcha_loading":      "Loading captcha...",
    "settings.no_auth":              "NO AUTH",

    /* ── sidebar / lefeder (left navigation) ──────────────── */
    "sidebar.brand":                 "WebRat",
    "sidebar.user_list":             "User list",
    "sidebar.builder":               "Builder",
    "sidebar.notifications":         "Notifications",
    "sidebar.forum":                 "Forum / Info",
    "sidebar.licenses":              "Licenses",
    "sidebar.settings":              "Settings",

    /* ── dm (private messages tab in community header) ──── */
    "dm.title":                       "DM",
    "dm.chats":                       "Chats",
    "dm.profile":                     "Profile",
    "dm.message":                     "Message",
    "dm.ban_history":                 "Ban history",

    /* ── subs / shop page (popups + section headers) ─────── */
    "subs.security_alert":           "Security alert",
    "subs.protect_email":            "To protect your account, please link your email.",
    "subs.go_settings":              "Go settings",
    "subs.deposit_balance":          "Deposit balance",
    "subs.item_information":         "Item information",
    "subs.payment_history":          "Payment history",
    "subs.your_balance":             "Your balance:",
    "subs.wallet":                   "Wallet",
    "subs.wallet_accepts":           "Accepts: TON(GRAM) and USDT (TON network)",
    "subs.choose_currency":          "Choose the currency",
    "subs.transfer_fee_warn":        "please take account the transfer fee",
    "subs.transfer_fee_warn2":       "please take into account the transfer fee",
    "subs.scan_to_pay":              "scan to pay",
    "subs.your_subs":                "Your subs",
    "subs.shop":                     "Shop",
    "subs.activate":                 "Activate",
    "subs.placeholder_activation_key":"activation key",
    "subs.warn_keys":                "do not activate keys obtained from non-official sources",
    "subs.item_name":                "ITEM NAME",
    "subs.active_sessions":          "active sessions",
    "subs.active_builds":            "active builds",
    "subs.proxy_on_users":           "proxy on users",
    "subs.description":              "DESCRIPTION",
    "subs.buy_with_balance":         "buy with balance",
    "subs.months_label":             "months:",
    "subs.total_label":              "total:",
    "subs.buy":                      "buy",
    "subs.lifetime":                 "lifetime",
    "subs.free_month.one":           "+{n} free month",
    "subs.free_month.other":         "+{n} free months",
    "subs.wallet_label":             "WALLET",
    "subs.amount_ton":               "AMOUNT (TON,GRAM)",
    "subs.status_label":             "STATUS",
    "subs.status_unpaid":            "unpaid",
    "subs.status_pending":           "pending",
    "subs.status_paid":              "paid",
    "subs.status_expired":           "expired",
    "subs.exact_amount":             "the exact amount must be transferred to the wallet",
    "subs.troubles":                 "troubles?",
    "subs.copy_wallet":              "Copy wallet",
    "subs.copy_amount":              "Copy amount",
    "subs.sub_until":                "Subscription until",
    "subs.sub_desc":                 "Subscription to our rat.",
    "subs.ended":                    "(ENDED)",
    "subs.trial":                    "(TRIAL)",
    "subs.renewal_required":         "(renewal required)",
    "subs.official_reseller":        "Official Reseller Contacts",
    "subs.dont_buy":                 "DON'T BUY FROM USERS OUTSIDE OF THE OFFICIAL RESELLER LIST, YOU WILL BE SCAMMED",
    "subs.reseller_name":            "NyashTeam",
    "subs.payment_label":            "Payment:",
    "subs.only_crypto":              "only crypto",
    "subs.contacts":                 "Contacts:",
    "subs.open_telegram":            "Open telegram",
    "subs.copy_label_wallet":        "Wallet",
    "subs.copy_label_amount":        "Amount",

    /* ── subs notifications ──────────────────────────────── */
    "subs.notif_congrats":           "Congratulations!!!",
    "subs.notif_sub_activated":      "Your subscription is activated.",
    "subs.notif_payment_error":      "payment error",
    "subs.notif_buy_error":          "buy error",
    "subs.notif_topup_error":        "topup error",
    "subs.notif_no_item":            "no item selected",
    "subs.notif_invalid_month":      "invalid month count",
    "subs.notif_no_balance":         "not enough balance",
    "subs.notif_topup_first":        "please top up your balance",
    "subs.notif_purchase_failed":    "purchase failed",
    "subs.notif_unknown_error":      "unknown error",
    "subs.notif_request_failed":     "request failed",
    "subs.notif_no_coins":           "no coins available",
    "subs.notif_copied":             "Copied",
    "subs.notif_copy_failed":        "Copy failed",
    "subs.notif_wallet_copied":      "wallet copied to clipboard",

    /* ── builder page (tab labels, popup titles, form labels) ──── */
    "builder.tab_builds":              "builds",
    "builder.tab_scripts":             "scripts",
    "builder.create_new_build":        "Create new build",
    "builder.create_new_script":       "Create new script",
    "builder.close_builder":           "Close builder",
    "builder.del_build_title":         "Delete build?",
    "builder.del_build_sub":           "This action cannot be undone.",
    "builder.are_you_sure":            "Are you sure?",
    "builder.build_info":              "Build info",
    "builder.scripts_title":           "Scripts",
    "builder.build_ready":             "build ready",
    "builder.build_saved":             "BUILD SAVED",
    "builder.archive_password":        "ARCHIVE PASSWORD :",
    "builder.no_info":                 "no info",
    "builder.blocked_geo":             "Blocked geo list",
    "builder.geo_hint":                "Use Alpha-2 country codes from",
    "builder.geo_link":                "here",
    "builder.new_notif_trigger":       "New notification trigger",

    /* build info table */
    "builder.lbl_id":                  "ID:",
    "builder.lbl_user_count":          "User count:",
    "builder.lbl_name":                "Name:",
    "builder.lbl_mutex":               "Mutex:",
    "builder.lbl_version":             "Version:",
    "builder.lbl_install":             "Install:",
    "builder.lbl_comment":             "Comment:",
    "builder.lbl_copy_count":          "Copy count:",
    "builder.lbl_color":               "Color:",
    "builder.lbl_autorun":             "Autorun:",
    "builder.lbl_created":             "Created:",
    "builder.lbl_autosteal":           "Autosteal:",
    "builder.lbl_force_adm":           "Force adm:",
    "builder.lbl_anti_mitm":           "Anti-Mitm:",
    "builder.lbl_anti_vps":            "Anti-VPS:",
    "builder.lbl_geoblock":            "GeoBlock:",
    "builder.lbl_victims":             "Victims:",

    /* build form */
    "builder.lbl_stub":                "Stub",
    "builder.lbl_hide_files":          "Hide files",
    "builder.lbl_anti_analysis":       "Anti-analysis",
    "builder.lbl_auto_steal":          "Auto Steal",
    "builder.lbl_force_admin":         "Force admin",
    "builder.lbl_extension":           "Extension",
    "builder.lbl_path":                "Path",
    "builder.lbl_autorun_key":         "Autorun Key",
    "builder.lbl_script":              "Script",
    "builder.lbl_method":              "Method",
    "builder.lbl_event":               "Event",

    /* select options (kept in sync with builder.dec.js switch cases) */
    "builder.opt_none":                "None",
    "builder.opt_once":                "Once",
    "builder.opt_every_connect":       "Every connect",
    "builder.opt_normal":              "Normal",
    "builder.opt_agressive":           "Agressive",
    "builder.opt_random":              "Random",
    "builder.opt_custom":              "Custom",
    "builder.opt_scheduler":           "Scheduler",
    "builder.opt_scheduler_registry":  "Scheduler + Registry",
    "builder.opt_registry":            "Registry",
    "builder.opt_steal":               "Steal",
    "builder.opt_install":             "Install",
    "builder.opt_connect":             "Connect",
    "builder.opt_anti_mitm":           "Anti Mitm",
    "builder.opt_anti_vps":            "Anti VPS",
    "builder.opt_full":                "Full",

    /* warnings */
    "builder.warn_anti_mitm":          "Anti Mitm is not recomended.",
    "builder.warn_default":            "Default settings are recommended.",
    "builder.warn_registry":           "Registry autorun is not recomended.",
    "builder.warn_no_autostart":       "Build will not be added to autostart.",

    /* buttons */
    "builder.btn_back":                "back",
    "builder.btn_save":                "save",
    "builder.btn_edit":                "edit",
    "builder.btn_create":              "Create",
    "builder.btn_scripts":             "Scripts",
    "builder.btn_geoblock":            "GeoBlock",
    "builder.btn_info":                "Info",
    "builder.btn_notification":        "Notification",
    "builder.btn_create_trigger":      "Create trigger",
    "builder.btn_delete":              "Delete",

    /* placeholders */
    "builder.placeholder_name":        "name",
    "builder.placeholder_mutex":       "mutex",
    "builder.placeholder_comment":     "comment",
    "builder.placeholder_autorun_key": "Autorun key",
    "builder.placeholder_build_id":    "build id",
    "builder.placeholder_select_method":"Select the method !",
    "builder.placeholder_method":      "method",

    /* notification trigger */
    "builder.attach_log":              "Attach Log",
    "builder.attach_screen":           "Attach Screen",

    /* confirm popup */
    "builder.confirm_title":           "Are you sure?",
    "builder.confirm_action_delete":   "delete build",

    /* plural: {n} victim(s) will become unavailable */
    "builder.victims_unavailable.one":   "{n} victim will become unavailable",
    "builder.victims_unavailable.other": "{n} victims will become unavailable",

    /* misc */
    "builder.no_builds":               "🡅No builds yet. Create a first one here.🡅",
    "builder.pass_not_found":          "not found",

    /* errors */
    "builder.err_mutex_empty":         "<b>mutex</b> field cannot be empty",
    "builder.err_path_empty":          "<b>path</b> field cannot be empty",
    "builder.err_autorun_key_empty":   "<b>autorun key</b> field cannot be empty",

    /* progress */
    "builder.progress_building":            "Build generation",
    "builder.progress_downloading":         "Downloading build: {pct}%",
    "builder.progress_downloading_pending": "Downloading build...",

    /* notifications */
    "builder.notif_builder":                "Builder",
    "builder.notif_builder_error":          "Builder Error",
    "builder.notif_build_deleted":          "build has been deleted",
    "builder.notif_protection_on":          "protection enabled",
    "builder.notif_protection_off":         "protection disabled",
    "builder.notif_settings_unchanged":     "settings has not been changed",
    "builder.notif_geoblock_saved":         "GeoBlock config saved",
    "builder.notif_geoblock_unchanged":     "GeoBlock config has not been changed",

    /* ── notify page (tab labels, popup titles, form labels) ──── */
    "notify.tab_control":            "control",
    "notify.tab_everyone":           "everyone",
    "notify.tab_build":              "build",
    "notify.tab_user":               "user",

    "notify.create_method":          "Create new method",
    "notify.create_trigger":         "Create new trigger",
    "notify.create_method_btn":      "Create method",
    "notify.create_trigger_btn":     "Create trigger",
    "notify.new_method_title":       "New notification method",
    "notify.new_trigger_title":      "New notification trigger",
    "notify.check":                  "check",

    "notify.method_telegram":        "telegram",
    "notify.method_discord":         "discord",

    "notify.placeholder_token":      "token",
    "notify.placeholder_chat_id":    "chat id",
    "notify.placeholder_webhook":    "WebHook",
    "notify.placeholder_user_id":    "user id",

    "notify.target_panel":           "everything in the panel",
    "notify.target_all_users":       "all users",
    "notify.adding_log":             "log",
    "notify.adding_screen":          "screen",

    "notify.lbl_event":              "Event:",
    "notify.lbl_target":             "Target:",

    "notify.token_valid":            "Token valid.",
    "notify.token_invalid":          "Token invalid.",

    "notify.err_fill_blanks":        "fill in the blanks",
    "notify.err_wrong_webhook":      "wrong webhook",

    "notify.notif_sent_title":       "message sent",
    "notify.notif_sent_body":        "make sure you got it",
    "notify.notif_rate_title":       "rate limit",
    "notify.notif_rate_body":        "plz wait",

    /* ── main panel page (top toolbar, filter, table settings, context menu) ── */

    /* top toolbar / header */
    "panel.online":                  "online",
    "panel.all":                     "all",
    "panel.offline":                 "offline",
    "panel.filter":                  "Filter",
    "panel.search":                  "search",
    "panel.reset_filter":            "reset filter",
    "panel.welcome_beta":            "Welcome to WebRat Beta!",
    "panel.dev_mode":                "DEV MODE",
    "panel.victims":                 "victims ",
    "panel.all_victims":             "all victims",
    "panel.victims_online":          "victims online",
    "panel.victims_offline":         "victims offline",
    "panel.loading":                 "loading",
    "panel.table_settings":          "Table settings",
    "panel.proxy_manager":           "Proxy manager",
    "panel.storage":                 "Storage",
    "panel.statistics":              "Statis",
    "panel.search_in_table":         "Search in table...",
    "panel.open_in_new_window":      "Open in new window",

    /* filter popup */
    "panel.filter_user_id":          "user id",
    "panel.filter_user_name":        "user name",
    "panel.filter_location":         "location",
    "panel.filter_build_ver":        "build ver",
    "panel.filter_pcname":           "pc-name",
    "panel.filter_active_win":       "active win",
    "panel.filter_ip":               "ip",
    "panel.filter_debut":            "debut",
    "panel.filter_savelog":          "savelog",
    "panel.filter_last_active":      "last active",
    "panel.filter_comment":          "comment",
    "panel.filter_os":               "os",
    "panel.filter_cpu":              "cpu",
    "panel.filter_ram":              "ram",
    "panel.filter_gpu":              "gpu",
    "panel.filter_build":            "build",
    "panel.filter_include":          "Include",
    "panel.filter_exclude":          "Exclude",
    "panel.filter_options":          "options",
    "panel.filter_match_any":        "Match Any",
    "panel.filter_match_all":        "Match All",

    /* table settings popup */
    "panel.popup_settings":          "Settings",
    "panel.colomns":                 "Colomns",
    "panel.check_status":            "status",
    "panel.check_username":          "username",
    "panel.check_admin_rights":      "admin rights",
    "panel.check_comment":           "comment",
    "panel.check_pcname":            "pc-name",
    "panel.check_window":            "window",
    "panel.check_last_active":       "last active",
    "panel.check_build_name":        "build name",
    "panel.check_build_version":     "build version",
    "panel.check_last_save_log":     "last save log",
    "panel.check_last_steal_log":    "last steal log",
    "panel.check_log_size":          "log size",
    "panel.check_id":                "id",
    "panel.check_ip":                "ip",
    "panel.check_os":                "os",
    "panel.check_cpu":               "cpu",
    "panel.check_ram":               "ram",
    "panel.check_gpu":               "gpu",
    "panel.check_debut":             "debut",
    "panel.check_build":             "build",
    "panel.check_hosting":           "hosting",
    "panel.check_location":          "location",
    "panel.check_afk_time":          "afk time",
    "panel.username_abbreviation":   "Username abbreviation",
    "panel.hide_duplicates":         "Hide duplicates",
    "panel.disable_canvas":          "Disable canvas",
    "panel.unsafe_remote_execution": "Unsafe remote execution",
    "panel.disable_color":          "Disable color",
    "panel.autoupdate_users":        "autoupdate users",
    "panel.none":                    "None",
    "panel.slow":                    "Slow",
    "panel.fast":                    "Fast",
    "panel.reset":                   "reset",

    /* proxy / storage / mass-action popups */
    "panel.proxy_list":              "Proxy list",
    "panel.reverse_proxy_socks5":    "Reverse proxy (SOCKS5)",
    "panel.port_forwarding":         "Port forvarding",
    "panel.server_data_storage":     "Server data storage",
    "panel.mass_actions_users":      "Mass actions with users",
    "panel.mass_online":             "online",
    "panel.mass_all":                "all",
    "panel.mass_offline":            "offline",
    "panel.mass_execute_stealer":    "Execute stealler",
    "panel.mass_save_log":           "Save log",
    "panel.mass_execute_file":       "Execute file",
    "panel.mass_execute_url":        "Execute url",
    "panel.mass_execute_command":    "Execute command",
    "panel.mass_execute_script":     "Execute script",
    "panel.mass_uninstall_build":    "Uninstall build",
    "panel.mass_kill_build":         "Kill build",
    "panel.mass_elevate":            "Elevate",
    "panel.mass_add":                "add",

    /* statistics window */
    "panel.statistics_title":        "STATISTICS",
    "panel.tab_adm":                 "adm",
    "panel.tab_build":               "build",
    "panel.tab_comment":             "comment",
    "panel.tab_country":             "country",
    "panel.tab_hosting":             "hosting",
    "panel.tab_uos":                 "uos",
    "panel.tab_version":             "version",

    /* context menu */
    "panel.connect":                 "Connect",
    "panel.execute":                 "Execute",
    "panel.log":                     "Log",
    "panel.build_menu":              "Build",
    "panel.database":                "Database",
    "panel.uninstall":               "Uninstall",
    "panel.elevate":                 "Elavate",
    "panel.kill":                    "Kill",
    "panel.save":                    "Save",
    "panel.save_log_action":         "Save log",
    "panel.steal":                   "Steal",
    "panel.delete":                  "Delete",
    "panel.select_file":             "Select file",
    "panel.exec_url":                "Exec URL",
    "panel.command":                 "Command",
    "panel.script":                  "Script",
    "panel.proxy":                   "Proxy",
    "panel.functional":              "Functional",
    "panel.comment_action":          "Comment",

    /* JS-side notifications (panel.dec.js) */
    "panel.contact_support":         "CONTACT SUPPORT",
    "panel.warning":                 "WARNING",
    "panel.no_auth":                 "NO AUTH",
    "panel.no_license":              "No license",
    "panel.new_user":                "NEW USER",
    "panel.ws_servers_not_found":    "ws servers not found!!!",
    "panel.proxy_deleted":           "proxy has been deleted",
    "panel.db_deleted_victims":      "Deleted {n} victims",
    "panel.db_victim_deleted":       "Victim deleted",
    "panel.upload_exec":             "Upload&Exec",
    "panel.error_uploading_file":    "Error uploading file",
    "panel.success":                 "success",
    "panel.error":                   "error",
    "panel.data_base":               "DataBase",
    "panel.redirecting_to_login":    "Redirecting to login",
    "panel.connect_button":          "Connect",
    "panel.requesting_execution":    "Requesting execution...",
    "panel.request_sent":            "Request sent ",
    "panel.no_users":                "😐 no users 😐",
    "panel.no_active_connections":   "No active connections",
    "panel.no_data":                 "No data",
    "panel.stats_groups":            "groups"
};
